# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/2018/Nexys4_Master.xdc

# IP: ip/FIFO16x7/FIFO16x7.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==FIFO16x7 || ORIG_REF_NAME==FIFO16x7} -quiet] -quiet
