# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/asroliveira/CloudStation/CR/2018/MultiClkDomainDemo/MultiClkDomainDemo.cache/wt [current_project]
set_property parent.project_path C:/Users/asroliveira/CloudStation/CR/2018/MultiClkDomainDemo/MultiClkDomainDemo.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_output_repo c:/Users/asroliveira/CloudStation/CR/2018/MultiClkDomainDemo/MultiClkDomainDemo.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  C:/Users/asroliveira/CloudStation/CR/2018/MultiClkDomainDemo/MultiClkDomainDemo.srcs/sources_1/new/CounterN.vhd
  C:/Users/asroliveira/CloudStation/CR/2018/MultiClkDomainDemo/MultiClkDomainDemo.srcs/sources_1/new/MultiClkDomainCore.vhd
  C:/Users/asroliveira/CloudStation/CR/2018/MultiClkDomainDemo/MultiClkDomainDemo.srcs/sources_1/new/MultiClkDomainDemo.vhd
}
read_ip -quiet C:/Users/asroliveira/CloudStation/CR/2018/MultiClkDomainDemo/MultiClkDomainDemo.srcs/sources_1/ip/FIFO16x7/FIFO16x7.xci
set_property used_in_implementation false [get_files -all c:/Users/asroliveira/CloudStation/CR/2018/MultiClkDomainDemo/MultiClkDomainDemo.srcs/sources_1/ip/FIFO16x7/FIFO16x7.xdc]
set_property used_in_implementation false [get_files -all c:/Users/asroliveira/CloudStation/CR/2018/MultiClkDomainDemo/MultiClkDomainDemo.srcs/sources_1/ip/FIFO16x7/FIFO16x7_ooc.xdc]

read_ip -quiet C:/Users/asroliveira/CloudStation/CR/2018/MultiClkDomainDemo/MultiClkDomainDemo.srcs/sources_1/ip/ClkGenerator/ClkGenerator.xci
set_property used_in_implementation false [get_files -all c:/Users/asroliveira/CloudStation/CR/2018/MultiClkDomainDemo/MultiClkDomainDemo.srcs/sources_1/ip/ClkGenerator/ClkGenerator_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/asroliveira/CloudStation/CR/2018/MultiClkDomainDemo/MultiClkDomainDemo.srcs/sources_1/ip/ClkGenerator/ClkGenerator.xdc]
set_property used_in_implementation false [get_files -all c:/Users/asroliveira/CloudStation/CR/2018/MultiClkDomainDemo/MultiClkDomainDemo.srcs/sources_1/ip/ClkGenerator/ClkGenerator_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/asroliveira/CloudStation/CR/2018/MultiClkDomainDemo/MultiClkDomainDemo.srcs/constrs_1/imports/2018/Nexys4_Master.xdc
set_property used_in_implementation false [get_files C:/Users/asroliveira/CloudStation/CR/2018/MultiClkDomainDemo/MultiClkDomainDemo.srcs/constrs_1/imports/2018/Nexys4_Master.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top MultiClkDomainDemo -part xc7a100tcsg324-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef MultiClkDomainDemo.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file MultiClkDomainDemo_utilization_synth.rpt -pb MultiClkDomainDemo_utilization_synth.pb"
