# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/catar/Desktop/git/vivado-xilinx-tutorials/dma/example1/DmaDemo/DmaDemo.srcs/sources_1/bd/mb_design/ip/mb_design_auto_pc_7/mb_design_auto_pc_7.xci
# IP: The module: 'mb_design_auto_pc_7' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/catar/Desktop/git/vivado-xilinx-tutorials/dma/example1/DmaDemo/DmaDemo.srcs/sources_1/bd/mb_design/ip/mb_design_auto_pc_7/mb_design_auto_pc_7_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mb_design_auto_pc_7'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: c:/Users/catar/Desktop/git/vivado-xilinx-tutorials/dma/example1/DmaDemo/DmaDemo.srcs/sources_1/bd/mb_design/ip/mb_design_auto_pc_7/mb_design_auto_pc_7.xci
# IP: The module: 'mb_design_auto_pc_7' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/catar/Desktop/git/vivado-xilinx-tutorials/dma/example1/DmaDemo/DmaDemo.srcs/sources_1/bd/mb_design/ip/mb_design_auto_pc_7/mb_design_auto_pc_7_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mb_design_auto_pc_7'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
