# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/asroliveira/CloudStation/CR/2018/MultiClkDomainDemo/MultiClkDomainDemo.srcs/sources_1/ip/ClkGenerator/ClkGenerator.xci
# IP: The module: 'ClkGenerator' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/asroliveira/CloudStation/CR/2018/MultiClkDomainDemo/MultiClkDomainDemo.srcs/sources_1/ip/ClkGenerator/ClkGenerator_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'ClkGenerator'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/asroliveira/CloudStation/CR/2018/MultiClkDomainDemo/MultiClkDomainDemo.srcs/sources_1/ip/ClkGenerator/ClkGenerator.xdc
# XDC: The top module name and the constraint reference have the same name: 'ClkGenerator'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/asroliveira/CloudStation/CR/2018/MultiClkDomainDemo/MultiClkDomainDemo.srcs/sources_1/ip/ClkGenerator/ClkGenerator_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ClkGenerator'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: C:/Users/asroliveira/CloudStation/CR/2018/MultiClkDomainDemo/MultiClkDomainDemo.srcs/sources_1/ip/ClkGenerator/ClkGenerator.xci
# IP: The module: 'ClkGenerator' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/asroliveira/CloudStation/CR/2018/MultiClkDomainDemo/MultiClkDomainDemo.srcs/sources_1/ip/ClkGenerator/ClkGenerator_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'ClkGenerator'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/asroliveira/CloudStation/CR/2018/MultiClkDomainDemo/MultiClkDomainDemo.srcs/sources_1/ip/ClkGenerator/ClkGenerator.xdc
# XDC: The top module name and the constraint reference have the same name: 'ClkGenerator'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/asroliveira/CloudStation/CR/2018/MultiClkDomainDemo/MultiClkDomainDemo.srcs/sources_1/ip/ClkGenerator/ClkGenerator_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ClkGenerator'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
