webtalk_init -webtalk_dir C:\\Users\\catar\\Nextcloud\\windowsToLinux\\example2\\CustomPeriphDemo\\webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "2020-04-29 22:33:27" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "Vitis v2019.2" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2019.2" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "Vitis" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "n8odsgmplv8g9uks9ch7pla503" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2019.2_4" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "4" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-4690 CPU @ 3.50GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3500 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "17.113 GB" -context "user_environment"
webtalk_register_client -client vitis
webtalk_add_data -client vitis -key uid -value "1588193695908" -context "vitis\\\\application/1588193695908"
webtalk_add_data -client vitis -key project_type -value "sdk" -context "vitis\\\\application/1588193695908"
webtalk_add_data -client vitis -key os -value "standalone" -context "vitis\\\\application/1588193695908"
webtalk_add_data -client vitis -key processor -value "microblaze" -context "vitis\\\\application/1588193695908"
webtalk_add_data -client vitis -key runtime -value "cpp" -context "vitis\\\\application/1588193695908"
webtalk_add_data -client vitis -key template -value "sdk" -context "vitis\\\\application/1588193695908"
webtalk_add_data -client vitis -key platform -value "NA" -context "vitis\\\\application/1588193695908"
webtalk_add_data -client vitis -key platform_type -value "NA" -context "vitis\\\\application/1588193695908"
webtalk_add_data -client vitis -key application_type -value "application" -context "vitis\\\\application/1588193695908"
webtalk_add_data -client vitis -key platform_source -value "dsa" -context "vitis\\\\application/1588193695908"
webtalk_add_data -client vitis -key device_family -value "NA" -context "vitis\\\\application/1588193695908"
webtalk_add_data -client vitis -key fpga -value "7a100t" -context "vitis\\\\application/1588193695908"
webtalk_transmit -clientid 3127628713 -regid "" -xml C:\\Users\\catar\\Nextcloud\\windowsToLinux\\example2\\CustomPeriphDemo\\webtalk\\usage_statistics_ext_vitis.xml -html C:\\Users\\catar\\Nextcloud\\windowsToLinux\\example2\\CustomPeriphDemo\\webtalk\\usage_statistics_ext_vitis.html -wdm C:\\Users\\catar\\Nextcloud\\windowsToLinux\\example2\\CustomPeriphDemo\\webtalk\\vitis_webtalk.wdm -intro "<H3>Vitis Usage Report</H3><BR>"
webtalk_terminate
