# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/catar/Desktop/git/cr-hashfunction/Md5Demo/Md5Demo.srcs/sources_1/bd/mb_design/ip/mb_design_axis_data_fifo_0_0/mb_design_axis_data_fifo_0_0.xci
# IP: The module: 'mb_design_axis_data_fifo_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/catar/Desktop/git/cr-hashfunction/Md5Demo/Md5Demo.srcs/sources_1/bd/mb_design/ip/mb_design_axis_data_fifo_0_0/mb_design_axis_data_fifo_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mb_design_axis_data_fifo_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: C:/Users/catar/Desktop/git/cr-hashfunction/Md5Demo/Md5Demo.srcs/sources_1/bd/mb_design/ip/mb_design_axis_data_fifo_0_0/mb_design_axis_data_fifo_0_0.xci
# IP: The module: 'mb_design_axis_data_fifo_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/catar/Desktop/git/cr-hashfunction/Md5Demo/Md5Demo.srcs/sources_1/bd/mb_design/ip/mb_design_axis_data_fifo_0_0/mb_design_axis_data_fifo_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mb_design_axis_data_fifo_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
