# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/mb_design/mb_design.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_design || ORIG_REF_NAME==mb_design} -quiet] -quiet

# IP: bd/mb_design/ip/mb_design_xbar_0/mb_design_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_design_xbar_0 || ORIG_REF_NAME==mb_design_xbar_0} -quiet] -quiet

# IP: bd/mb_design/ip/mb_design_microblaze_0_axi_periph_0/mb_design_microblaze_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_design_microblaze_0_axi_periph_0 || ORIG_REF_NAME==mb_design_microblaze_0_axi_periph_0} -quiet] -quiet

# IP: bd/mb_design/ip/mb_design_microblaze_0_axi_intc_0/mb_design_microblaze_0_axi_intc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_design_microblaze_0_axi_intc_0 || ORIG_REF_NAME==mb_design_microblaze_0_axi_intc_0} -quiet] -quiet

# IP: bd/mb_design/ip/mb_design_microblaze_0_xlconcat_0/mb_design_microblaze_0_xlconcat_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_design_microblaze_0_xlconcat_0 || ORIG_REF_NAME==mb_design_microblaze_0_xlconcat_0} -quiet] -quiet

# IP: bd/mb_design/ip/mb_design_mdm_1_0/mb_design_mdm_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_design_mdm_1_0 || ORIG_REF_NAME==mb_design_mdm_1_0} -quiet] -quiet

# IP: bd/mb_design/ip/mb_design_clk_wiz_1_0/mb_design_clk_wiz_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_design_clk_wiz_1_0 || ORIG_REF_NAME==mb_design_clk_wiz_1_0} -quiet] -quiet

# IP: bd/mb_design/ip/mb_design_rst_clk_wiz_1_100M_0/mb_design_rst_clk_wiz_1_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_design_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==mb_design_rst_clk_wiz_1_100M_0} -quiet] -quiet

# IP: bd/mb_design/ip/mb_design_axi_gpio_0_0/mb_design_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_design_axi_gpio_0_0 || ORIG_REF_NAME==mb_design_axi_gpio_0_0} -quiet] -quiet

# IP: bd/mb_design/ip/mb_design_axi_gpio_1_0/mb_design_axi_gpio_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_design_axi_gpio_1_0 || ORIG_REF_NAME==mb_design_axi_gpio_1_0} -quiet] -quiet

# IP: bd/mb_design/ip/mb_design_axi_gpio_2_0/mb_design_axi_gpio_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_design_axi_gpio_2_0 || ORIG_REF_NAME==mb_design_axi_gpio_2_0} -quiet] -quiet

# IP: bd/mb_design/ip/mb_design_axi_gpio_3_0/mb_design_axi_gpio_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_design_axi_gpio_3_0 || ORIG_REF_NAME==mb_design_axi_gpio_3_0} -quiet] -quiet

# IP: bd/mb_design/ip/mb_design_axi_uartlite_0_0/mb_design_axi_uartlite_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_design_axi_uartlite_0_0 || ORIG_REF_NAME==mb_design_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/mb_design/ip/mb_design_axi_timer_0_0/mb_design_axi_timer_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_design_axi_timer_0_0 || ORIG_REF_NAME==mb_design_axi_timer_0_0} -quiet] -quiet

# IP: bd/mb_design/ip/mb_design_fit_timer_0_0/mb_design_fit_timer_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_design_fit_timer_0_0 || ORIG_REF_NAME==mb_design_fit_timer_0_0} -quiet] -quiet

# IP: bd/mb_design/ip/mb_design_axi_emc_0_0/mb_design_axi_emc_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_design_axi_emc_0_0 || ORIG_REF_NAME==mb_design_axi_emc_0_0} -quiet] -quiet

# IP: bd/mb_design/ip/mb_design_microblaze_0_1/mb_design_microblaze_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_design_microblaze_0_1 || ORIG_REF_NAME==mb_design_microblaze_0_1} -quiet] -quiet

# IP: bd/mb_design/ip/mb_design_dlmb_v10_1/mb_design_dlmb_v10_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_design_dlmb_v10_1 || ORIG_REF_NAME==mb_design_dlmb_v10_1} -quiet] -quiet

# IP: bd/mb_design/ip/mb_design_ilmb_v10_1/mb_design_ilmb_v10_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_design_ilmb_v10_1 || ORIG_REF_NAME==mb_design_ilmb_v10_1} -quiet] -quiet

# IP: bd/mb_design/ip/mb_design_dlmb_bram_if_cntlr_1/mb_design_dlmb_bram_if_cntlr_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_design_dlmb_bram_if_cntlr_1 || ORIG_REF_NAME==mb_design_dlmb_bram_if_cntlr_1} -quiet] -quiet

# IP: bd/mb_design/ip/mb_design_ilmb_bram_if_cntlr_1/mb_design_ilmb_bram_if_cntlr_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_design_ilmb_bram_if_cntlr_1 || ORIG_REF_NAME==mb_design_ilmb_bram_if_cntlr_1} -quiet] -quiet

# IP: bd/mb_design/ip/mb_design_lmb_bram_1/mb_design_lmb_bram_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_design_lmb_bram_1 || ORIG_REF_NAME==mb_design_lmb_bram_1} -quiet] -quiet

# IP: bd/mb_design/ip/mb_design_axi_dma_0_0/mb_design_axi_dma_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_design_axi_dma_0_0 || ORIG_REF_NAME==mb_design_axi_dma_0_0} -quiet] -quiet

# IP: bd/mb_design/ip/mb_design_axis_data_fifo_0_0/mb_design_axis_data_fifo_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_design_axis_data_fifo_0_0 || ORIG_REF_NAME==mb_design_axis_data_fifo_0_0} -quiet] -quiet

# IP: bd/mb_design/ip/mb_design_Md5HashFunction_0_0/mb_design_Md5HashFunction_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_design_Md5HashFunction_0_0 || ORIG_REF_NAME==mb_design_Md5HashFunction_0_0} -quiet] -quiet

# IP: bd/mb_design/ip/mb_design_auto_pc_8/mb_design_auto_pc_8.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_design_auto_pc_8 || ORIG_REF_NAME==mb_design_auto_pc_8} -quiet] -quiet

# IP: bd/mb_design/ip/mb_design_auto_pc_0/mb_design_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_design_auto_pc_0 || ORIG_REF_NAME==mb_design_auto_pc_0} -quiet] -quiet

# IP: bd/mb_design/ip/mb_design_auto_pc_1/mb_design_auto_pc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_design_auto_pc_1 || ORIG_REF_NAME==mb_design_auto_pc_1} -quiet] -quiet

# IP: bd/mb_design/ip/mb_design_auto_pc_2/mb_design_auto_pc_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_design_auto_pc_2 || ORIG_REF_NAME==mb_design_auto_pc_2} -quiet] -quiet

# IP: bd/mb_design/ip/mb_design_auto_pc_3/mb_design_auto_pc_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_design_auto_pc_3 || ORIG_REF_NAME==mb_design_auto_pc_3} -quiet] -quiet

# IP: bd/mb_design/ip/mb_design_auto_pc_4/mb_design_auto_pc_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_design_auto_pc_4 || ORIG_REF_NAME==mb_design_auto_pc_4} -quiet] -quiet

# IP: bd/mb_design/ip/mb_design_auto_pc_5/mb_design_auto_pc_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_design_auto_pc_5 || ORIG_REF_NAME==mb_design_auto_pc_5} -quiet] -quiet

# IP: bd/mb_design/ip/mb_design_auto_pc_6/mb_design_auto_pc_6.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_design_auto_pc_6 || ORIG_REF_NAME==mb_design_auto_pc_6} -quiet] -quiet

# IP: bd/mb_design/ip/mb_design_auto_pc_7/mb_design_auto_pc_7.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_design_auto_pc_7 || ORIG_REF_NAME==mb_design_auto_pc_7} -quiet] -quiet

# XDC: bd/mb_design/mb_design_ooc.xdc
