# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/catar/Desktop/git/vivado-xilinx-tutorials/PlatformWithExtMemory/PlatformWithExtMemory.srcs/sources_1/bd/mb_design/ip/mb_design_ilmb_bram_if_cntlr_1/mb_design_ilmb_bram_if_cntlr_1.xci
# IP: The module: 'mb_design_ilmb_bram_if_cntlr_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/catar/Desktop/git/vivado-xilinx-tutorials/PlatformWithExtMemory/PlatformWithExtMemory.srcs/sources_1/bd/mb_design/ip/mb_design_ilmb_bram_if_cntlr_1/mb_design_ilmb_bram_if_cntlr_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mb_design_ilmb_bram_if_cntlr_1'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/Users/catar/Desktop/git/vivado-xilinx-tutorials/PlatformWithExtMemory/PlatformWithExtMemory.srcs/sources_1/bd/mb_design/ip/mb_design_ilmb_bram_if_cntlr_1/mb_design_ilmb_bram_if_cntlr_1.xci
# IP: The module: 'mb_design_ilmb_bram_if_cntlr_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/catar/Desktop/git/vivado-xilinx-tutorials/PlatformWithExtMemory/PlatformWithExtMemory.srcs/sources_1/bd/mb_design/ip/mb_design_ilmb_bram_if_cntlr_1/mb_design_ilmb_bram_if_cntlr_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mb_design_ilmb_bram_if_cntlr_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
